//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestTracker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuestTrackerEDMXEntities : DbContext
    {
        public QuestTrackerEDMXEntities()
            : base("name=QuestTrackerEDMXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<QuestObjective> QuestObjectives { get; set; }
        public virtual DbSet<Quest> Quests { get; set; }
        public virtual DbSet<Game> Games { get; set; }
    }
}
